// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traveler.Data;

namespace Traveler.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220409031831_type")]
    partial class type
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Traveler.Models.Pelanggan", b =>
                {
                    b.Property<string>("nik")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("kartu_vaksin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nama_pelanggan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("no_telp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .HasColumnType("text");

                    b.HasKey("nik");

                    b.ToTable("Tb_Pelanggan");
                });

            modelBuilder.Entity("Traveler.Models.Pesawat", b =>
                {
                    b.Property<string>("kode_pesawat")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Bandara_asal")
                        .HasColumnType("text");

                    b.Property<string>("Bandara_tujuan")
                        .HasColumnType("text");

                    b.Property<string>("Maskapai")
                        .HasColumnType("text");

                    b.Property<DateTime>("berangkat")
                        .HasColumnType("datetime");

                    b.Property<int>("harga")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasColumnType("text");

                    b.HasKey("kode_pesawat");

                    b.ToTable("Tb_Pesawat");
                });

            modelBuilder.Entity("Traveler.Models.Roles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tb_Roles");
                });

            modelBuilder.Entity("Traveler.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RolesId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("RolesId");

                    b.ToTable("Tb_User");
                });

            modelBuilder.Entity("Traveler.Models.transaksi", b =>
                {
                    b.Property<string>("id_transaksi")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Pelanggannik")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("pesawatkode_pesawat")
                        .HasColumnType("varchar(767)");

                    b.HasKey("id_transaksi");

                    b.HasIndex("Pelanggannik");

                    b.HasIndex("pesawatkode_pesawat");

                    b.ToTable("Tb_Transaksi");
                });

            modelBuilder.Entity("Traveler.Models.User", b =>
                {
                    b.HasOne("Traveler.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Traveler.Models.transaksi", b =>
                {
                    b.HasOne("Traveler.Models.Pelanggan", "Pelanggan")
                        .WithMany()
                        .HasForeignKey("Pelanggannik");

                    b.HasOne("Traveler.Models.Pesawat", "pesawat")
                        .WithMany()
                        .HasForeignKey("pesawatkode_pesawat");

                    b.Navigation("Pelanggan");

                    b.Navigation("pesawat");
                });
#pragma warning restore 612, 618
        }
    }
}
